plugins:
  - rubocop-rails
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/admin/**'
    - 'config/environments/**'
    - 'lib/tasks/**'
    - 'spec/controllers/**'

Layout/LineLength:
  Exclude:
    - 'app/models/**'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
    - 'app/helpers/**'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
    - 'app/models/**'
Rails/StrongParametersExpect:
  Enabled: false